In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
data = pd.read_csv("C:\\Users\\hp\\Desktop\\BOOTCAMP\\Python\\Week 8\\Telco_Customer_Churn.csv")
data

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7027    Male              0     Yes        Yes      24          Yes   
7028  Female              0     Yes        Yes      72          Yes   
7029  Female              0     Yes        Yes      11           No   
7030    Male              1     Yes         No       4          Yes   
7031    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7027               Yes             DSL            Yes           No   
7028               Yes     Fiber optic             No          Yes   
7029  No phone service             DSL            Yes           No   
7030               Yes     Fiber optic             No           No   
7031                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7027              Yes         Yes         Yes             Yes        One year   
7028              Yes          No         Yes             Yes        One year   
7029               No          No          No              No  Month-to-month   
7030               No          No          No              No  Month-to-month   
7031              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  \
0                 Yes           Electronic check           29.85   
1                  No               Mailed check           56.95   
2                 Yes               Mailed check           53.85   
3                  No  Bank transfer (automatic)           42.30   
4                 Yes           Electronic check           70.70   
...               ...                        ...             ...   
7027              Yes               Mailed check           84.80   
7028              Yes    Credit card (automatic)          103.20   
7029              Yes           Electronic check           29.60   
7030              Yes               Mailed check           74.40   
7031              Yes  Bank transfer (automatic)          105.65   

      TotalCharges Churn  
0            29.85    No  
1          1889.50    No  
2           108.15   Yes  
3          1840.75    No  
4           151.65   Yes  
...            ...   ...  
7027       1990.50    No  
7028       7362.90    No  
7029        346.45    No  
7030        306.60   Yes  
7031       6844.50    No  

[7032 rows x 20 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7032 non-null   object 
 1   SeniorCitizen     7032 non-null   int64  
 2   Partner           7032 non-null   object 
 3   Dependents        7032 non-null   object 
 4   tenure            7032 non-null   int64  
 5   PhoneService      7032 non-null   object 
 6   MultipleLines     7032 non-null   object 
 7   InternetService   7032 non-null   object 
 8   OnlineSecurity    7032 non-null   object 
 9   OnlineBackup      7032 non-null   object 
 10  DeviceProtection  7032 non-null   object 
 11  TechSupport       7032 non-null   object 
 12  StreamingTV       7032 non-null   object 
 13  StreamingMovies   7032 non-null   object 
 14  Contract          7032 non-null   object 
 15  PaperlessBilling  7032 non-null   object 
 16  PaymentMethod     7032 non-null   object 


In [4]:
data['Churn'].replace(to_replace='Yes', value=1, inplace=True)
data['Churn'].replace(to_replace='No',  value=0, inplace=True)

In [5]:
X = data.drop(columns = ['Churn'])
X

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7027    Male              0     Yes        Yes      24          Yes   
7028  Female              0     Yes        Yes      72          Yes   
7029  Female              0     Yes        Yes      11           No   
7030    Male              1     Yes         No       4          Yes   
7031    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7027               Yes             DSL            Yes           No   
7028               Yes     Fiber optic             No          Yes   
7029  No phone service             DSL            Yes           No   
7030               Yes     Fiber optic             No           No   
7031                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7027              Yes         Yes         Yes             Yes        One year   
7028              Yes          No         Yes             Yes        One year   
7029               No          No          No              No  Month-to-month   
7030               No          No          No              No  Month-to-month   
7031              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  
0                 Yes           Electronic check           29.85         29.85  
1                  No               Mailed check           56.95       1889.50  
2                 Yes               Mailed check           53.85        108.15  
3                  No  Bank transfer (automatic)           42.30       1840.75  
4                 Yes           Electronic check           70.70        151.65  
...               ...                        ...             ...           ...  
7027              Yes               Mailed check           84.80       1990.50  
7028              Yes    Credit card (automatic)          103.20       7362.90  
7029              Yes           Electronic check           29.60        346.45  
7030              Yes               Mailed check           74.40        306.60  
7031              Yes  Bank transfer (automatic)          105.65       6844.50  

[7032 rows x 19 columns]

In [6]:
Y = data['Churn']
Y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [7]:
#transforming categorical variables into dummy variables
X = pd.get_dummies(X)
X

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Female  \
0                 0       1           29.85         29.85              1   
1                 0      34           56.95       1889.50              0   
2                 0       2           53.85        108.15              0   
3                 0      45           42.30       1840.75              0   
4                 0       2           70.70        151.65              1   
...             ...     ...             ...           ...            ...   
7027              0      24           84.80       1990.50              0   
7028              0      72          103.20       7362.90              1   
7029              0      11           29.60        346.45              1   
7030              1       4           74.40        306.60              0   
7031              0      66          105.65       6844.50              0   

      gender_Male  Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  \
0               0           0            1              1               0   
1               1           1            0              1               0   
2               1           1            0              1               0   
3               1           1            0              1               0   
4               0           1            0              1               0   
...           ...         ...          ...            ...             ...   
7027            1           0            1              0               1   
7028            0           0            1              0               1   
7029            0           0            1              0               1   
7030            1           0            1              1               0   
7031            1           1            0              1               0   

      ...  StreamingMovies_Yes  Contract_Month-to-month  Contract_One year  \
0     ...                    0                        1                  0   
1     ...                    0                        0                  1   
2     ...                    0                        1                  0   
3     ...                    0                        0                  1   
4     ...                    0                        1                  0   
...   ...                  ...                      ...                ...   
7027  ...                    1                        0                  1   
7028  ...                    1                        0                  1   
7029  ...                    0                        1                  0   
7030  ...                    0                        1                  0   
7031  ...                    1                        0                  0   

      Contract_Two year  PaperlessBilling_No  PaperlessBilling_Yes  \
0                     0                    0                     1   
1                     0                    1                     0   
2                     0                    0                     1   
3                     0                    1                     0   
4                     0                    0                     1   
...                 ...                  ...                   ...   
7027                  0                    0                     1   
7028                  0                    0                     1   
7029                  0                    0                     1   
7030                  0                    0                     1   
7031                  1                    0                     1   

      PaymentMethod_Bank transfer (automatic)  \
0                                           0   
1                                           0   
2                                           0   
3                                           1   
4                                           0   
...                                       ...   
7027                                        0  

In [8]:
#splitting data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [9]:
#Scaling data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
#SVM w/ Linear kernel
from sklearn.svm import SVC
classifier_l = SVC(kernel = "linear", random_state=0)
classifier_l.fit(X_train, Y_train)

SVC(kernel='linear', random_state=0)

In [11]:
y_pred = classifier_l.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
from sklearn.metrics import  accuracy_score, classification_report, confusion_matrix
cm = metrics.confusion_matrix(Y_test, y_pred) 
print(cm)
accuracy_l = metrics.accuracy_score(Y_test, y_pred) 
print("Accuracy score:",accuracy_l)
precision = metrics.precision_score(Y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(Y_test, y_pred) 
print("Recall score:",recall)

[[920 121]
 [169 197]]
Accuracy score: 0.7938877043354655
Precision score: 0.6194968553459119
Recall score: 0.5382513661202186


In [13]:
#SVM w/ RBF kernel
classifier_rbf = SVC(kernel = "rbf", random_state=0)
classifier_rbf.fit(X_train, Y_train)

SVC(random_state=0)

In [14]:
y_pred = classifier_rbf.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
cm = metrics.confusion_matrix(Y_test, y_pred) 
print(cm)
accuracy_rbf = metrics.accuracy_score(Y_test, y_pred) 
print("Accuracy score:",accuracy_rbf)
precision = metrics.precision_score(Y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(Y_test, y_pred) 
print("Recall score:",recall)

[[935 106]
 [182 184]]
Accuracy score: 0.7953091684434968
Precision score: 0.6344827586206897
Recall score: 0.5027322404371585


In [16]:
#Decision Tree classifier
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = "entropy", random_state=0)
classifier_dt.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [17]:
y_pred = classifier_dt.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [18]:
cm = metrics.confusion_matrix(Y_test, y_pred) 
print(cm)
accuracy_dt = metrics.accuracy_score(Y_test, y_pred) 
print("Accuracy score:",accuracy_dt)
precision = metrics.precision_score(Y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(Y_test, y_pred) 
print("Recall score:",recall)

[[824 217]
 [181 185]]
Accuracy score: 0.7171286425017769
Precision score: 0.4601990049751244
Recall score: 0.505464480874317


In [19]:
#RandomForest Classifier

from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=100, criterion="gini", random_state=0)
classifier_rf.fit(X_train, Y_train)

RandomForestClassifier(random_state=0)

In [20]:
y_pred = classifier_rf.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
cm = metrics.confusion_matrix(Y_test, y_pred) 
print(cm)
accuracy_rf = metrics.accuracy_score(Y_test, y_pred) 
print("Accuracy score:",accuracy_rf)
precision = metrics.precision_score(Y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(Y_test, y_pred) 
print("Recall score:",recall)

[[930 111]
 [183 183]]
Accuracy score: 0.7910447761194029
Precision score: 0.6224489795918368
Recall score: 0.5


In [22]:
model_list=["SVM(Linear Kernel)", "SVM(RBF Kernel)", "Decision Tree", "RandomForest"]
accuracy_list = [accuracy_l, accuracy_rbf, accuracy_dt, accuracy_rf]
scores_df = pd.DataFrame()

scores_df["Accuracy"]=accuracy_list
scores_df.index=model_list

scores_df.sort_values(by=["Accuracy"], ascending=False)

Accuracy
SVM(RBF Kernel)     0.795309
SVM(Linear Kernel)  0.793888
RandomForest        0.791045
Decision Tree       0.717129

In [23]:
#10-fold Cross Validation on SVM w/linear kernel

from sklearn.model_selection import cross_val_score 
scores = cross_val_score(classifier_l, X_train, Y_train, cv=10)
mean_l = scores.mean()
print('CV scores:', scores)
print('Mean Accuracy:',mean_l)

CV scores: [0.80639432 0.80106572 0.79218472 0.80994671 0.78685613 0.80960854
 0.82384342 0.79181495 0.78647687 0.79003559]
Mean Accuracy: 0.7998226961562044


In [24]:
#10-fold Cross Validation on SVM w/ RBF kernel
from sklearn.model_selection import cross_val_score 
scores = cross_val_score(classifier_rbf, X_train, Y_train, cv=10)
mean_rbf = scores.mean()
print('CV scores:', scores)
print('Mean Accuracy:',mean_rbf)

CV scores: [0.79218472 0.78863233 0.80817052 0.80106572 0.79040853 0.80427046
 0.8202847  0.78113879 0.78291815 0.79181495]
Mean Accuracy: 0.7960888857986258


In [25]:
#10-fold Cross Validation on Decision Tree classifier
from sklearn.model_selection import cross_val_score 
scores = cross_val_score(classifier_dt, X_train, Y_train, cv=10)
mean_dt = scores.mean()
print('CV scores:', scores)
print('Mean Accuracy:',mean_dt)

CV scores: [0.71936057 0.69804618 0.74600355 0.74955595 0.74955595 0.74021352
 0.75800712 0.72241993 0.71708185 0.76690391]
Mean Accuracy: 0.7367148537006252


In [26]:
#10-fold Cross Validation on Random Forest classifier
from sklearn.model_selection import cross_val_score 
scores = cross_val_score(classifier_rf, X_train, Y_train, cv=10)
mean_rf = scores.mean()
print('CV scores:', scores)
print('Mean Accuracy:',mean_rf)

CV scores: [0.76909414 0.77087034 0.77797513 0.81172291 0.79928952 0.78647687
 0.81494662 0.79003559 0.79181495 0.80782918]
Mean Accuracy: 0.792005524547575


In [27]:
model_list=["SVM(Linear Kernel)", "SVM(RBF Kernel)", "Decision Tree", "RandomForest"]
accuracy_list = [mean_l, mean_rbf, mean_dt, mean_rf]
scores_df = pd.DataFrame()

scores_df["Mean Accuracy of 10-fold CV"]=accuracy_list
scores_df.index=model_list

scores_df.sort_values(by=["Mean Accuracy of 10-fold CV"], ascending=False)

Mean Accuracy of 10-fold CV
SVM(Linear Kernel)                     0.799823
SVM(RBF Kernel)                        0.796089
RandomForest                           0.792006
Decision Tree                          0.736715